# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_time'], 'permissions': (('can_comment', 'Can_comment'),)},
        ),
    ]
